package com.tomfricks.hook.keyboard

import android.graphics.Bitmap
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.tomfricks.hook.api.ReplyError

/**
 * Process-wide state for one *session* of "screenshot -> replies".
 *
 * It deliberately does *not* live on [HookKeyboardService]: the IME is
 * created and destroyed constantly, and the screenshot usually arrives while
 * no input view exists at all. Keeping the session here means detection can run,
 * finish, and store replies with no keyboard on screen — whichever IME
 * instance shows up next simply renders what is already here.
 *
 * A session is an ordered transcript ([items]) that keeps growing: each new
 * screenshot is appended as a follow-up image, replies land under it, and a
 * picked reply becomes a sent bubble. Only the "+" button ([reset]) clears it.
 *
 * ## Who is allowed to spend a generation
 *
 * A generation is only ever started by *claiming* one here — [claimForScreenshot]
 * for the automatic round a new screenshot earns, [claimForRetry] for an explicit
 * tap on the action pill. Both hand back a [Generation] or null, and null means
 * "do not call the server". That single rule is what keeps the keyboard idle:
 * a screenshot is worth exactly one automatic round, so re-showing the IME —
 * which Android does constantly, including right after a reply is committed —
 * can no longer kick off a round of its own.
 *
 * Every claim carries a token, and results are only applied while that token is
 * still the live one ([onSuggestions], [onFailure], [onAllowanceExhausted] all
 * take it). A round superseded by a newer screenshot, or by "+", lands in the
 * bin instead of overwriting fresher state.
 */
object RizzSession {

    enum class Status {
        /** Nothing captured yet. */
        IDLE,

        /** Screenshot in hand, replies being written. */
        GENERATING,

        /** Replies ready (or partly sent). */
        SHOWING,

        /** Generation failed. */
        ERROR
    }

    /** One entry in the ongoing chat transcript, rendered top-to-bottom. */
    sealed interface TranscriptItem {
        /** A captured screenshot, shown as an attachment card. */
        data class Screenshot(val id: Long, val bitmap: Bitmap) : TranscriptItem

        /** A reply the user picked and committed — no longer tappable. */
        data class SentReply(val text: String) : TranscriptItem

        /** A pending suggestion the user can still tap to send. */
        data class Suggestion(val text: String) : TranscriptItem

        /** The animated "typing" bubble shown while replies are generating. */
        data object Typing : TranscriptItem
    }

    /**
     * A granted permission to call the server exactly once.
     *
     * [token] identifies the round; hand it back with the result so a stale
     * response — one whose screenshot has since been superseded — is dropped
     * rather than rendered.
     */
    data class Generation(val token: Long, val screenshot: Bitmap)

    /** A screenshot older than this is no longer worth generating from. */
    const val SCREENSHOT_TTL_MS = 2 * 60 * 1000L

    /** How long a finished session stays on screen. */
    private const val SUGGESTIONS_TTL_MS = 5 * 60 * 1000L

    /**
     * "Nothing here": no screenshot, no round in flight. Ids and tokens both
     * start at 1, so this is never a real one.
     */
    private const val NONE = 0L

    var status by mutableStateOf(Status.IDLE)
        private set

    /** The ordered transcript: screenshots, sent replies, suggestions, typing. */
    var items by mutableStateOf<List<TranscriptItem>>(emptyList())
        private set

    var error by mutableStateOf<String?>(null)
        private set

    /**
     * Set when the server refused a generation because the lifetime free
     * allowance is spent (HTTP 402). Sticky on purpose: it survives [reset] and
     * only clears once the user is entitled, so the keyboard keeps showing the
     * upsell instead of a "Rizz" button that can only fail.
     */
    var paywallRequired by mutableStateOf(false)
        private set

    var screenshotAt: Long = 0L
        private set

    private var suggestionsAt: Long = 0L

    private var nextScreenshotId = 1L
    private var nextGenerationToken = 1L

    /** The newest screenshot in the session, or 0 when there is none. */
    private var latestScreenshotId = NONE

    /** The newest screenshot an automatic round has already been claimed for. */
    private var autoGeneratedScreenshotId = NONE

    /** Token of the round currently in flight, or [NONE]. */
    private var activeToken = NONE

    /** The most recent screenshot in the session, used for "generate more". */
    val latestScreenshot: Bitmap?
        get() = items.filterIsInstance<TranscriptItem.Screenshot>().lastOrNull()?.bitmap

    /** True while the newest screenshot is recent enough to generate replies from. */
    val hasFreshScreenshot: Boolean
        get() = latestScreenshot != null &&
            System.currentTimeMillis() - screenshotAt < SCREENSHOT_TTL_MS

    /** True while any tappable suggestion is still pending. */
    val hasPendingSuggestions: Boolean
        get() = items.any { it is TranscriptItem.Suggestion }

    /** True when the session still holds fresh, worth-showing replies. */
    val hasFreshSuggestions: Boolean
        get() = hasPendingSuggestions &&
            System.currentTimeMillis() - suggestionsAt < SUGGESTIONS_TTL_MS

    /** True once the session has any reply activity (sent or pending). */
    val hasReplies: Boolean
        get() = items.any { it is TranscriptItem.SentReply || it is TranscriptItem.Suggestion }

    /** True while a round is in flight, whoever started it. */
    val isGenerating: Boolean
        @Synchronized get() = activeToken != NONE

    /**
     * A new screenshot continues the session instead of resetting it: any
     * un-picked suggestions from the previous screenshot are discarded (they
     * were about the old screen, and the hidden context never held them) and
     * the new screenshot is appended as a follow-up image.
     *
     * This only records the screenshot. Generation starts when someone claims
     * it with [claimForScreenshot], so the two can't disagree about whether a
     * round is owed.
     */
    @Synchronized
    fun onScreenshot(bitmap: Bitmap) {
        val id = nextScreenshotId++
        latestScreenshotId = id
        screenshotAt = System.currentTimeMillis()
        error = null
        items = items.filterNot { it is TranscriptItem.Suggestion || it is TranscriptItem.Typing } +
            TranscriptItem.Screenshot(id, bitmap)
        if (status == Status.ERROR) status = if (hasReplies) Status.SHOWING else Status.IDLE
    }

    /**
     * Claim the one automatic round the newest screenshot is owed.
     *
     * Returns null — meaning *do not call the server* — when the screenshot has
     * already had its round, when there is no screenshot, or when the one we
     * have is too old to still describe what's on screen. Both the detector and
     * the IME call this, and exactly one of them can win.
     *
     * A screenshot that arrives mid-round supersedes it: the claim succeeds and
     * the older round's token stops being live, so its reply is discarded when
     * it lands.
     */
    @Synchronized
    fun claimForScreenshot(): Generation? {
        if (latestScreenshotId == autoGeneratedScreenshotId) return null
        val screenshot = latestScreenshot ?: return null
        if (!hasFreshScreenshot) return null
        autoGeneratedScreenshotId = latestScreenshotId
        return startGeneration(screenshot)
    }

    /**
     * Claim a repeat round on the screenshot already in hand — the action pill,
     * i.e. the user asking in so many words for three more replies.
     *
     * Unlike [claimForScreenshot] this ignores whether the screenshot has been
     * generated from before; it only refuses while a round is in flight, or
     * when there's no fresh screenshot to work from.
     */
    @Synchronized
    fun claimForRetry(): Generation? {
        if (activeToken != NONE) return null
        val screenshot = latestScreenshot ?: return null
        if (!hasFreshScreenshot) return null
        autoGeneratedScreenshotId = latestScreenshotId
        return startGeneration(screenshot)
    }

    private fun startGeneration(screenshot: Bitmap): Generation {
        val token = nextGenerationToken++
        activeToken = token
        error = null
        items = items.filterNot { it is TranscriptItem.Suggestion || it is TranscriptItem.Typing } +
            TranscriptItem.Typing
        status = Status.GENERATING
        return Generation(token, screenshot)
    }

    /** True while [token] is still the round the UI is waiting on. */
    @Synchronized
    fun isLive(token: Long): Boolean = token != NONE && token == activeToken

    @Synchronized
    fun onSuggestions(token: Long, replies: List<String>) {
        if (!finish(token)) return
        suggestionsAt = System.currentTimeMillis()
        error = null
        items = items.filterNot { it is TranscriptItem.Typing } +
            replies.map { TranscriptItem.Suggestion(it) }
        status = Status.SHOWING
    }

    @Synchronized
    fun onFailure(token: Long, reason: ReplyError) {
        if (!finish(token)) return
        showFailure(reason)
    }

    /**
     * A failure with no round behind it — the user tapped the pill with nothing
     * to generate from.
     */
    @Synchronized
    fun onUnstartable(reason: ReplyError) {
        showFailure(reason)
    }

    private fun showFailure(reason: ReplyError) {
        error = reason.userMessage
        items = items.filterNot { it is TranscriptItem.Typing }
        status = Status.ERROR
    }

    /**
     * The free allowance ran out. Not an error — the transcript stays exactly
     * as it is and the keyboard swaps its action for an upgrade prompt.
     */
    @Synchronized
    fun onAllowanceExhausted(token: Long) {
        if (!finish(token)) return
        error = null
        items = items.filterNot { it is TranscriptItem.Typing }
        paywallRequired = true
        status = if (items.isEmpty()) Status.IDLE else Status.SHOWING
    }

    /**
     * Retire [token]. False means the round was superseded or cancelled while
     * it was in flight, and its result must not touch the transcript.
     */
    private fun finish(token: Long): Boolean {
        if (token == NONE || token != activeToken) return false
        activeToken = NONE
        return true
    }

    /** Called once the user is Pro, so the upsell disappears without a restart. */
    fun clearPaywallRequired() {
        paywallRequired = false
    }

    /**
     * Keep a tapped reply and drop the rest: the chosen suggestion becomes a
     * sent bubble at the bottom of the transcript and every other pending
     * suggestion is removed.
     *
     * Nothing here re-arms generation. The screenshot has had its round, so the
     * keyboard now sits idle until the user takes another screenshot or asks
     * for more replies outright.
     */
    @Synchronized
    fun markSent(reply: String) {
        items = items.filterNot { it is TranscriptItem.Suggestion } +
            TranscriptItem.SentReply(reply)
        suggestionsAt = System.currentTimeMillis()
        error = null
        status = Status.SHOWING
    }

    /** Drop a session that is too old to be about the conversation on screen. */
    @Synchronized
    fun clearIfStale() {
        if (activeToken == NONE && !hasFreshSuggestions && !hasFreshScreenshot) {
            reset()
        }
    }

    @Synchronized
    fun reset() {
        status = Status.IDLE
        items = emptyList()
        error = null
        screenshotAt = 0L
        suggestionsAt = 0L
        latestScreenshotId = NONE
        autoGeneratedScreenshotId = NONE
        // Any round still in flight belongs to the chat we just closed: let its
        // token go dead so the reply is dropped instead of landing in the new one.
        activeToken = NONE
        // paywallRequired is deliberately untouched: a new chat doesn't buy the
        // user more free generations.
    }
}
